### ISSUE TITLE
Ondra - Create form updates

### ISSUE THREAD

**Issue by dacerondrej** [Antalyan/riddleshare#36]
- [x] - File uploading in `CreateRiddleForm`
- [x] - Linkování uživatelů v případě private hádanky
- [x] - Vlajka a obtížnost v `CreateRiddleForm`
- [x] - Figma update - dialog Wrong answers
- [x] - Implementovat `MyRiddleDetail`

**Comment by Antalyan** [comment]
+ Ukázat nějakou chybu uživateli, když vkládání selže

**Comment by Antalyan** [comment]
Updatovat kopírovaný link na celou adresu tzn. včetně prefixu
